# Generated by Django 2.1.7 on 2019-03-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0002_auto_20190308_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
