# Generated by Django 2.1.7 on 2019-03-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0003_recipe_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_required',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
