# Generated by Django 2.1.7 on 2019-03-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0004_auto_20190308_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_required',
            field=models.IntegerField(default=1),
        ),
    ]
